version: '3.8'
services:
  grails-app:
    build:
      context: ./backend
      dockerfile: DockerfileGrails
    ports:
      - "8081:8080"
    volumes:
      - ./backend:/app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: PostgreDB
      DB_USER: tomas
      DB_PASSWORD: miau123
    depends_on:
      - db
    networks:
      - Buk_network

  db:
    container_name: PostgreDB
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tomas
      POSTGRES_DB: PostgreDB
      POSTGRES_PASSWORD: miau123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - Buk_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8084:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: miau123
    depends_on:
      - db
    networks:
      - Buk_network

  vue-app:
    build:
      context: ./frontend
      dockerfile: DockerfileVueJS
    ports:
      - "8082:8080"  # Puerto 8082 para la aplicación Vue.js
    volumes:
      - ./frontend:/app
    depends_on:
      - grails-app
    networks:
      - Buk_network

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8083:8080"  # Jenkins UI en el puerto 8083
      - "50000:50000"  # Puerto para agentes de Jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - Buk_network

volumes:
  postgres_data:
    name: postgres_data
  jenkins_data:
    name: jenkins_data

networks:
  Buk_network:
    name: Buk_network
