version: '3.8'
services:
  grails-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - GRADLE_USER_HOME=/cache

  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - grails-app
