version: '3.8'
services:
  grails-app:
    build: ./backend
    ports:
      - "8081:8080"
    volumes:
      - ./backend:/app
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - Buk_network

  db:
    container_name: PostgreDB
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tomas
      POSTGRES_DB: PostgreDB
      POSTGRES_PASSWORD: miau123
    networks:
      - Buk_network

  vue-app:
    build:
      context: ./frontend
      dockerfile: DockerfileVueJS
    ports:
      - "8082:8080"  # Cambiado para evitar conflictos, Vue ahora usa 8082 en el host
    volumes:
      - ./frontend:/app
    depends_on:
      - grails-app
    networks:
      - Buk_network

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8083:8080"  # Jenkins ahora en el puerto 8083
      - "50000:50000"  # Puerto para agentes de Jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - Buk_network

volumes:
  jenkins_data:  # Definir el volumen para persistir los datos de Jenkins

networks:
  Buk_network:
    name: Buk_network
