info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  controllers:
    defaultScope: singleton
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
  server:
    port: 8081
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
      - text/html
      - application/xhtml+xml
      js: text/javascript
      json:
      - application/json
      - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
dataSource:
  dbCreate: update
  url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  driverClassName: org.postgresql.Driver
  username: tomas
  password: miau123
  dialect: org.hibernate.dialect.PostgreSQLDialect

hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
